### ISSUE TITLE
ruby-saml 0.8 line does not allow multiple values for attributes

### ISSUE THREAD

**Issue by mattspatola** [PracticallyGreen/omniauth-saml#38]
Ran into this issue when receiving an attribute with multiple values.  The 0.8 line of ruby-saml does not allow multiple values for any attributes and will instead take the first value in these cases.  By bumping the dependency to '~> 0.9.1', we get the new Attributes objects that allow us to get an array of values without changing the default behavior when using hash access.

I implemented it on [our fork](https://github.com/lumoslabs/omniauth-saml), specifically on [this commit](https://github.com/lumoslabs/omniauth-saml/commit/d4d68fe4ccec11c947d7541f63349484aa570b68) to bump the version (and bump its gem version) and [this commit](https://github.com/lumoslabs/omniauth-saml/commit/4a8b20fbb1afb8af49b039a2d3c3ef0a6f59886d) to do a quick, dirty hack to fix the specs (and update the Gemfile.lock).

**Comment by bpedro** [comment]
I just released v1.4.0 (https://github.com/PracticallyGreen/omniauth-saml/releases/tag/v1.4.0) which uses ruby-saml 1.0.0.

I hope that fixes this issue.

Thanks!
