### ISSUE TITLE
Check for success never happens because of earlier check for name_id

### ISSUE THREAD

**Issue by djfpaagman** [PracticallyGreen/omniauth-saml#55]
Right now there is no check on the StatusCode, which [can returns multiple failures][1]. Instead the first error that is triggered is "SAML response missing 'name_id'' while there is actually might be more going on underneath, making it hard to debug.

[ruby-saml does check it][2] in its validation, but since the check for `name_id` happens earlier, you will never see it. I'm not really sure what the right solution would be, I think moving up the `valid?` call could do the trick but not sure of the consequences of that.

I'm happy to explore the possibilities but checking here first.

[1]: https://msdn.microsoft.com/en-us/library/hh269642.aspx
[2]: https://github.com/onelogin/ruby-saml/blob/a331dac9fd3bcfa716c599dbe4e961e4638e2d14/lib/onelogin/ruby-saml/response.rb#L264

**Comment by djfpaagman** [comment]
Ping

**Comment by md5** [comment]
:+1:

**Comment by ilikepi** [comment]
:+1:

**Comment by supernova32** [comment]
@djfpaagman thanks for this, I merged #60
